export const stoicQuotes = [
  "Control the controllable.",
  "Focus is freedom.",
  "Discipline equals peace.",
  "Start now, not later.",
  "Action over anxiety.",
  "Progress, not perfection.",
  "Suffer the discipline or suffer regret.",
  "The obstacle is the way.",
  "Character over comfort.",
  "Show up every day.",
  "Master your morning, master your life.",
  "Silence the excuses.",
  "Consistency is key.",
  "Hard work in silence.",
  "Build, don't broadcast.",
  "Present moment, full focus.",
  "Execute without emotion.",
  "Your future self is watching.",
  "No days off from growth.",
  "Virtue through action.",
  "Mind over comfort.",
  "Embrace the grind.",
  "Excellence is a habit.",
  "Stay hungry, stay disciplined.",
  "Focus on what matters.",
  "Less talk, more work.",
  "Earn your rest.",
  "Detach from outcomes.",
  "Process over results.",
  "Build in the dark.",
  "Patience is power.",
  "Trust the process.",
  "Stay calm, stay focused.",
  "Make today count.",
  "Rise above distractions.",
  "Strength through struggle.",
  "Momentum builds empires.",
  "Every rep matters.",
  "Silence is strength.",
  "Work speaks louder.",
  "Master yourself first.",
  "Compound your efforts.",
  "Small wins daily.",
  "Stay in your lane.",
  "Control your response.",
  "Focus fuels success.",
  "Chase excellence, not applause.",
  "Discipline breeds freedom.",
  "Outwork your doubts.",
  "Quality over quantity.",
]

export function getRandomQuote(): string {
  return stoicQuotes[Math.floor(Math.random() * stoicQuotes.length)]
}
